# -*- coding: utf-8 -*-
"""Expriement 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1krunpUjknW5T6eO1FNrYc2IwWMIA8J8l
"""

import pandas as pd

CSV_PATH = "placement_predict_50k_Dataset.csv"

import pandas as pd
df = pd.read_csv('/content/placement_predict_50k Dataset.csv')

print("FIRST 5 ROWS")

print(df.head(5))

print("\nDATASET SHAPE")

print(df.shape)

print("\nCOLUMN NAMES")

print(df.columns)

print("\nDATA TYPES")

print(df.dtypes)

print("\nDATASET INFORMATION")

df.info()

print("\nSTATISTICAL SUMMARY")

print(df.describe())

print("\nMISSING VALUES")

print(df.isnull().sum())

print("\nDUPLICATE ROWS")

print(df.duplicated().sum())

print("\nPLACEMENT STATUS DISTRIBUTION")

print(df["PlacementStatus"].value_counts())

print("\nPLACEMENT STATUS PERCENTAGE")

print(df["PlacementStatus"].value_counts(normalize=True) * 100)