# -*- coding: utf-8 -*-
"""week2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xHlVStcDmU7KKqLFEKDiU7Hic1E1Ewz6

### STEP 1: Upload the CSV file from your Desktop
"""

from google.colab import files

uploaded = files.upload()
# -> A "Choose Files" button will appear.
# -> Click it, browse to your Desktop, and select:
#    placement_predict_50k Dataset.csv

"""### STEP 2: Import all required libraries"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from matplotlib.backends.backend_pdf import PdfPages

sns.set_style("whitegrid")   # optional: gives cleaner-looking charts

"""### STEP 3: Read the dataset using pandas"""

df = pd.read_csv("placement_predict_50k Dataset.csv")

"""### STEP 4: Display the dataset (first look)"""

print("First 5 rows of the dataset:")
display(df.head())          # use display() in Colab; use print(df.head()) elsewhere

"""### STEP 5: Check shape, columns, info, and missing values"""

print("\nShape of dataset (rows, columns):", df.shape)
print("\nColumns in the dataset:", df.columns.tolist())
print("\nDataset Info:")
df.info()
print("\nMissing values per column:")
print(df.isnull().sum())

"""### STEP 6: Handle Numerical and Categorical Columns"""

# Identify numerical and categorical columns
num_cols = df.select_dtypes(include=np.number).columns.tolist()
cat_cols = df.select_dtypes(include='object').columns.tolist()

# Exclude 'StudentID' from numerical columns as it's an identifier
if 'StudentID' in num_cols:
    num_cols.remove('StudentID')

print("Numerical Columns:", num_cols)
print("Categorical Columns:", cat_cols)

"""### STEP 7: Impute Missing Values"""

# The dataset has missing values in a few columns.
# We will impute numerical columns with the median.

for col in ['Workshops', 'AptitudeTestScore', 'SoftSkillsRating', 'CodingTestScore', 'MockInterviewScore']:
    if col in num_cols:
        df[col].fillna(df[col].median(), inplace=True)

print("\nMissing values after imputation:")
print(df.isnull().sum())

"""### STEP 8: Visualize Missingness (Page 1 of PDF)"""

# Visualize missingness as a heatmap
fig1 = plt.figure(figsize=(10, 6))
sns.heatmap(df.isnull(), cbar=False, cmap='viridis')
plt.title('Missingness Heatmap (After Imputation)')
plt.show()

"""### STEP 9: Plot Histograms (Page 2 of PDF)"""

# Plot histograms for numerical columns
fig2, axes2 = plt.subplots(2, 3, figsize=(18, 10))

hist_cols = ['CGPA', 'AttendancePercent', 'AptitudeTestScore', 'SoftSkillsRating', 'CodingTestScore', 'MockInterviewScore']

for i, col in enumerate(hist_cols):
    row, colpos = divmod(i, 3)
    sns.histplot(df[col], kde=True, ax=axes2[row, colpos])
    axes2[row, colpos].set_title(f'Distribution of {col}')

plt.tight_layout()
plt.show()

"""### STEP 9 (PAGE 3): Placement Rate by Stream"""

# Calculate placement rate by stream
placement_rate = df.groupby('Stream')['PlacementStatus'].mean().sort_values(ascending=False)

fig3 = plt.figure(figsize=(10, 6))
sns.barplot(x=placement_rate.index, y=placement_rate.values, palette='viridis')
plt.title('Placement Rate by Stream')
plt.xlabel('Stream')
plt.ylabel('Placement Rate')
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.show()

print("\nPlacement Rate by Stream:")
print(placement_rate.round(2))

"""### STEP 11: Boxplots (Page 5 of PDF)"""

fig5, axes5 = plt.subplots(2, 3, figsize=(15, 8))

for i, col in enumerate(hist_cols):
    row, colpos = divmod(i, 3)
    sns.boxplot(y=df[col], ax=axes5[row, colpos], color='lightcoral')
    axes5[row, colpos].set_title(f'Boxplot of {col}')

plt.tight_layout()
plt.show()

"""### STEP 12: Combine all 5 pages into ONE PDF using PdfPages"""

pdf = PdfPages('EDA_Report.pdf')

pdf.savefig(fig1)   # Page 1: Missingness Heatmap
pdf.savefig(fig2)   # Page 2: Six Histograms
pdf.savefig(fig3)   # Page 3: Placement Rate by Stream
pdf.savefig(fig4)   # Page 4: Correlation Heatmap
pdf.savefig(fig5)   # Page 5: Boxplots

pdf.close()

print("\nEDA_Report.pdf created successfully with 5 pages!")

"""### STEP 13: Download the generated PDF to your computer"""

from google.colab import files
files.download('EDA_Report.pdf')

"""### STEP 10: Correlation Heatmap (Page 4 of PDF)"""

fig4 = plt.figure(figsize=(10, 8))

numeric_df = df.select_dtypes(include=['int64', 'float64'])
corr_matrix = numeric_df.corr()

sns.heatmap(corr_matrix, annot=True, fmt='.2f', cmap='coolwarm',
            square=True, linewidths=0.5)
plt.title('Correlation Heatmap - Numerical Features')
plt.tight_layout()
plt.show()